kind: Service
metadata:
  name: nginx
spec:
  mode: WEB
  isPublic: true
  config:
    upstream:
      container:
        image: nginx
        port: 80
---
kind: Service
metadata:
  name: google
spec:
  mode: WEB
  isPublic: true
  config:
    upstream:
      url: https://www.google.com
---
kind: Service
metadata:
  name: nginx-anonymous
spec:
  mode: WEB
  isPublic: true
  isAnonymous: true
  config:
    upstream:
      container:
        image: nginx
        port: 80
---
kind: Service
metadata:
  name: pg
spec:
  mode: TCP
  port: 5432
  config:
    upstream:
      container:
        image: postgres
        port: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: password
---
kind: Service
metadata:
  name: pg.production
spec:
  mode: TCP
  port: 5432
  config:
    upstream:
      container:
        image: postgres
        port: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: password
---
kind: Service
metadata:
  name: postgres-main
spec:
  mode: POSTGRES
  port: 5432
  config:
    upstream:
      url: postgres://octelium-pg-postgresql.default.svc
    postgres:
      user: octelium
      database: octelium
      auth:
        password:
          fromSecret: pg
---
kind: Service
metadata:
  name: essh
spec:
  mode: SSH
  config:
    ssh:
      eSSHMode: true